### PR TITLE
enable github actions

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by pevik** [comment]
Anton, thanks for adding it now, it's good to have it and I'm for merging this.
But FYI we're just talking about upstreaming it in LTP directly [1], people in that thread (including me) are for adding it directly to LTP repository [2]. We still use Travis CI, docker and podman based (so we compile with common distros) [3], so after merging into LTP there it will have to be adapted. I'm planning to introduce `make check` target for library, this would go under it as well and `make check` would be added (conditionally, when asked by some switch) in `build.sh`.

Other task is to convert testing to github actions (I don't like the web UI of github actions thus I've been postponing this work), but I'll have to soon find a time for it due docker pull rate limit error (we have workaround for it, but that don't prevent occasional failures).

@b10n1k FYI

[1] https://lists.linux.it/pipermail/ltp/2021-April/022081.html
[2] https://github.com/linux-test-project/ltp/
[3] https://github.com/linux-test-project/ltp/blob/master/.travis.yml

**Comment by asmorodskyi** [comment]
> Anton, thanks for adding it now, it's good to have it and I'm for merging this.
> But FYI we're just talking about upstreaming it in LTP directly [1], people in that thread (including me) are for adding it directly to LTP repository [2]. We still use Travis CI, docker and podman based (so we compile with common distros) [3], so after merging into LTP there it will have to be adapted. I'm planning to introduce `make check` target for library, this would go under it as well and `make check` would be added (conditionally, when asked by some switch) in `build.sh`.
> 
> Other task is to convert testing to github actions (I don't like the web UI of github actions thus I've been postponing this work), but I'll have to soon find a time for it due docker pull rate limit error (we have workaround for it, but that don't prevent occasional failures).
> 
> @b10n1k FYI
> 
> [1] https://lists.linux.it/pipermail/ltp/2021-April/022081.html
> [2] https://github.com/linux-test-project/ltp/
> [3] https://github.com/linux-test-project/ltp/blob/master/.travis.yml

Thanks for giving me bigger picture . I IMHO it make sense to take this PR as short-term approach which could give us benefits just after merge and all what you said as long-term . I mean I don't see how what you said is stopping us from merge this PR

**Review by pevik — APPROVED** [review]
`Reviewed-by: Petr Vorel <pvorel@suse.cz>`

**Comment by metan-ucw** [comment]
Looks good to me

**Pull request closed without merging**
