### PR TITLE
make: Remove tags target (was: Pass correct --extra to ctags)

### PR DESCRIPTION
**Pull request by yangx-jy**
Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

### CODE REVIEW

**Comment by yangx-jy** [comment]
Hi @metan-ucw @pevik 

Is it necessary to add 'make tags' into ci.yml?

**Comment by pevik** [comment]
Thank you for fixing this. If we want to keep ctags support, it should be also in `ci.yml` (and you should add  `Fixes: 766b8db Introduce perltidy and perlcritic")`).

But I'd be for removing ctag support. @metan-ucw @cfconrad @wangli5665 @richiejp any opinion?

**Comment by wangli5665** [comment]
> But I'd be for removing ctag support. @metan-ucw @cfconrad @wangli5665 @richiejp any opinion?

+1, I slightly think that not very necessary to support ctag, because, IMHO it might not part of the project.

**Comment by wangli5665** [comment]
> Thank you for fixing this. If we want to keep ctags support, it should be also in `ci.yml` (and you should add `Fixes: 766b8db Introduce perltidy and perlcritic")`).

BTW, if we decide to support, better to add "/ctags" in the .gitignore file.

**Comment by yangx-jy** [comment]
> +1, I slightly think that not very necessary to support ctags, because, IMHO it might not part of the project.

Yes, `ctags` is a tool which helps track the definition of function conveniently.
I perfer to keep it in Makefile and add it in .gitignore, but don't add it into ci.yml.

**Comment by pevik** [comment]
> > +1, I slightly think that not very necessary to support ctags, because, IMHO it might not part of the project.
> 
> Yes, `ctags` is a tool which helps track the definition of function conveniently.
> I perfer to keep it in Makefile and add it in .gitignore, but don't add it into ci.yml.

Well, if we keep it, I'd also add it to CI. Ideally software should be 100% tested (impossible), thus why refusing an easy test coverage? I meant to remove it, but it does not harm to have it. But keep in mind, that we're planning to move the tool into LTP git soon (probably after fixing https://github.com/metan-ucw/runltp-ng/issues/31 and https://github.com/metan-ucw/runltp-ng/issues/32), and we don't support ctags generation in LTP itself.

**Comment by yangx-jy** [comment]
> Well, if we keep it, I'd also add it to CI. Ideally software should be 100% tested (impossible), thus why refusing an easy test coverage? I meant to remove it, but it does not harm to have it. But keep in mind, that we're planning to move the tool into LTP git soon (probably after fixing #31 and #32), and we don't support ctags generation in LTP itself.

OK, Let's remove it directly.

**Review by pevik — APPROVED** [review]
LGTM, just please add a note that `--extras` option is was wrong, but instead of fixing it to `--extra` we decided to remove the target.
`Reviewed-by: Petr Vorel <pvorel@suse.cz>`

**Comment by wangli5665** [comment]
Reviewed-by: Li Wang <liwang@redhat.com>

**Comment by yangx-jy** [comment]
> LGTM, just please add a note that `--extras` option is was wrong, but instead of fixing it to `--extra` we decided to remove the target.

Done.

**Comment by metan-ucw** [comment]
Looks good, acked.

**Pull request closed without merging**
